wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    framework: lightgbm
    is_jupyter_run: true
    python_version: 3.6.8
bagging_fraction:
  desc: null
  value: 1
feature_fraction:
  desc: null
  value: 0.9
max_depth:
  desc: null
  value: 200
method:
  desc: null
  value: bayes
min_child_weight:
  desc: null
  value: 1
min_split_gain:
  desc: null
  value: 0.001
num_leaves:
  desc: null
  value: 100
